#DB_USERNAME=sunsin
#DB_NAME=sunsindb
#DB_PASSWORD=mysecretpassword
#DB_HOST=locallhost
#DB_PORT=5432

DB_USERNAME = 'neondb_owner'
DB_NAME = 'neondb'
DB_PASSWORD = 'npg_Zvu2Wmloir1e'
DB_HOST = 'ep-little-frost-a1v0a2e4-pooler.ap-southeast-1.aws.neon.tech'
DB_PORT = '5432'

